# Generated by Django 3.1.2 on 2023-01-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetVrai', '0003_auto_20230123_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
